-- Project Aether — Migration 0001: Initial schema
--
-- This is the versioned equivalent of supabase/schema.sql. Run via:
--   supabase db push
-- or apply manually in the Supabase SQL Editor.
--
-- Tables: sensor_readings, alerts
-- RLS: read-only for authenticated users; writes come from the
--      ingest-mqtt Edge Function using the service_role key.
-- Realtime: enabled on alerts for live dashboard updates (G5).

-- ---------------------------------------------------------------------
-- sensor_readings — one row per ESP32 MQTT message (every 5s per node)
-- ---------------------------------------------------------------------
create table if not exists sensor_readings (
  id uuid primary key default gen_random_uuid(),
  node_id text not null,
  recorded_at timestamptz not null default now(),
  temperature numeric,
  humidity numeric,
  heat_index numeric,           -- Steadman heat index (°C), computed by ingest-mqtt
  air_quality numeric,          -- 0-100 pollution percentage
  luminosity numeric,
  comfort_index numeric,        -- alias for heat_index (kept for backward compat)
  comfort_status text check (comfort_status in ('OPTIMAL', 'FAIR', 'POOR'))
);

create index if not exists sensor_readings_recorded_at_idx
  on sensor_readings (recorded_at desc);

create index if not exists sensor_readings_node_idx
  on sensor_readings (node_id, recorded_at desc);

alter table sensor_readings enable row level security;

create policy "Authenticated users can read sensor readings"
  on sensor_readings for select
  to authenticated
  using (true);

-- ---------------------------------------------------------------------
-- alerts — threshold breaches generated by the alerting engine (Phase C)
-- ---------------------------------------------------------------------
create table if not exists alerts (
  id uuid primary key default gen_random_uuid(),
  node_id text not null,
  severity text not null check (severity in ('info', 'warning', 'critical')),
  title text not null,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists alerts_created_at_idx
  on alerts (created_at desc);

alter table alerts enable row level security;

create policy "Authenticated users can read alerts"
  on alerts for select
  to authenticated
  using (true);

-- Enable Supabase Realtime on alerts so the dashboard's AlertsPanel
-- receives live INSERT events without polling (closes G5).
alter publication supabase_realtime add table alerts;

-- Enable Realtime on sensor_readings so the dashboard receives live
-- readings without mqtt.js in the browser bundle (closes G7). The
-- ingest-mqtt Edge Function is the sole writer; the browser subscribes
-- to INSERT events here via Supabase Realtime.
alter publication supabase_realtime add table sensor_readings;
